class Property {
  final String id;
  final String name;
  final String location;
  final double price;
  final String imageUrl;
  final String description;
  final int bedrooms;
  final int bathrooms;
  final String propertyArea;
  final int cctv;
  final int parkingSpots;
  final int year;
  final Agent agent;
  final double rating;
  final String reviewerName;
  final String reviewerImage;
  final String propertyType; // 'apartment', 'house'
  final String listingType;  // 'shortlet', 'rent'

  Property({
    required this.id,
    required this.name,
    required this.location,
    required this.price,
    required this.imageUrl,
    required this.description,
    required this.bedrooms,
    required this.bathrooms,
    required this.propertyArea,
    required this.cctv,
    required this.parkingSpots,
    required this.year,
    required this.agent,
    required this.rating,
    required this.reviewerName,
    required this.reviewerImage,
    this.propertyType = 'apartment',
    this.listingType = 'shortlet',
  });
}

class Agent {
  final String name;
  final String email;
  final String imageUrl;
  final String? phone;

  Agent({
    required this.name,
    required this.email,
    required this.imageUrl,
    this.phone,
  });
}

final _defaultAgent = Agent(
  name: 'LS Woltoh',
  email: 'lswoltoh07@gmail.com',
  imageUrl: 'https://i.pravatar.cc/150?img=12',
);

class PropertyData {
  static List<Property> getAbujaProperties() {
    return [
      Property(
        id: '1',
        name: 'Green Hangout Place',
        location: 'Wuse 2, Abuja',
        price: 85000.00,
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        description: 'Luxurious apartment in Wuse 2 with modern amenities, stunning views and easy access to shopping centers and restaurants.',
        bedrooms: 3,
        bathrooms: 2,
        propertyArea: '120 sqm',
        cctv: 10,
        parkingSpots: 2,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.5,
        reviewerName: 'Kw Ahayan',
        reviewerImage: 'https://i.pravatar.cc/150?img=33',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: '2',
        name: 'Elegant Apartment',
        location: 'Maitama, Abuja',
        price: 18000.00,
        imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
        description: 'Luxurious floor apartment in Maitama with spacious rooms and premium finishes throughout.',
        bedrooms: 4,
        bathrooms: 3,
        propertyArea: '180 sqm',
        cctv: 10,
        parkingSpots: 6,
        year: 2025,
        agent: _defaultAgent,
        rating: 4.8,
        reviewerName: 'Md Liakat',
        reviewerImage: 'https://i.pravatar.cc/150?img=1',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: '3',
        name: 'Modern Luxury Villa',
        location: 'Asokoro, Abuja',
        price: 140000.00,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        description: 'A stunning modern villa in Asokoro with premium amenities and breathtaking views of the city.',
        bedrooms: 5,
        bathrooms: 4,
        propertyArea: '250 sqm',
        cctv: 15,
        parkingSpots: 4,
        year: 2023,
        agent: _defaultAgent,
        rating: 4.7,
        reviewerName: 'Kw Ahayan',
        reviewerImage: 'https://i.pravatar.cc/150?img=33',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: '4',
        name: 'Cozy Studio Apartment',
        location: 'Garki, Abuja',
        price: 40000.00,
        imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
        description: 'Perfect studio for short stays in Garki, close to major business districts.',
        bedrooms: 1,
        bathrooms: 1,
        propertyArea: '45 sqm',
        cctv: 5,
        parkingSpots: 1,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.3,
        reviewerName: 'Md Liakat',
        reviewerImage: 'https://i.pravatar.cc/150?img=1',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: '5',
        name: 'Executive Penthouse',
        location: 'Maitama, Abuja',
        price: 200000.00,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        description: 'Luxurious penthouse with panoramic city views, perfect for executives seeking premium accommodation.',
        bedrooms: 6,
        bathrooms: 5,
        propertyArea: '350 sqm',
        cctv: 20,
        parkingSpots: 8,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.9,
        reviewerName: 'Kw Ahayan',
        reviewerImage: 'https://i.pravatar.cc/150?img=33',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      // Houses for rent – Abuja
      Property(
        id: 'abj-h1',
        name: '4 Bedroom Detached House',
        location: 'Gwarinpa, Abuja',
        price: 350000.00,
        imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        description: 'Spacious 4-bedroom detached house in Gwarinpa estate with a large compound, boys quarters, and 24/7 security.',
        bedrooms: 4,
        bathrooms: 3,
        propertyArea: '220 sqm',
        cctv: 8,
        parkingSpots: 3,
        year: 2022,
        agent: _defaultAgent,
        rating: 4.6,
        reviewerName: 'Emeka Obi',
        reviewerImage: 'https://i.pravatar.cc/150?img=15',
        propertyType: 'house',
        listingType: 'rent',
      ),
      Property(
        id: 'abj-h2',
        name: '3 Bedroom Terrace House',
        location: 'Life Camp, Abuja',
        price: 200000.00,
        imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        description: 'Modern 3-bedroom terrace house in a serene Life Camp estate with fitted kitchen and all-rooms en-suite.',
        bedrooms: 3,
        bathrooms: 3,
        propertyArea: '160 sqm',
        cctv: 6,
        parkingSpots: 2,
        year: 2023,
        agent: _defaultAgent,
        rating: 4.5,
        reviewerName: 'Ngozi Adeyemi',
        reviewerImage: 'https://i.pravatar.cc/150?img=20',
        propertyType: 'house',
        listingType: 'rent',
      ),
      Property(
        id: 'abj-h3',
        name: '5 Bedroom Luxury Mansion',
        location: 'Asokoro, Abuja',
        price: 650000.00,
        imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
        description: 'Stunning luxury mansion in Asokoro with private pool, cinema room, and state-of-the-art smart home technology.',
        bedrooms: 5,
        bathrooms: 5,
        propertyArea: '400 sqm',
        cctv: 20,
        parkingSpots: 6,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.9,
        reviewerName: 'Chukwuma Nwosu',
        reviewerImage: 'https://i.pravatar.cc/150?img=25',
        propertyType: 'house',
        listingType: 'rent',
      ),
    ];
  }

  static List<Property> getLagosProperties() {
    return [
      Property(
        id: 'lagos-1',
        name: 'Luxury Apartment Lekki',
        location: 'Lekki Phase 1, Lagos',
        price: 120000.00,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        description: 'Modern luxury apartment in Lekki Phase 1, close to the beach and major shopping centers.',
        bedrooms: 3,
        bathrooms: 2,
        propertyArea: '140 sqm',
        cctv: 12,
        parkingSpots: 2,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.6,
        reviewerName: 'Guest',
        reviewerImage: 'https://i.pravatar.cc/150?img=33',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: 'lagos-2',
        name: 'Victoria Island Penthouse',
        location: 'Victoria Island, Lagos',
        price: 250000.00,
        imageUrl: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800',
        description: 'Stunning penthouse with ocean views in Victoria Island, perfect for business executives.',
        bedrooms: 4,
        bathrooms: 3,
        propertyArea: '200 sqm',
        cctv: 15,
        parkingSpots: 3,
        year: 2023,
        agent: _defaultAgent,
        rating: 4.9,
        reviewerName: 'Guest',
        reviewerImage: 'https://i.pravatar.cc/150?img=1',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: 'lagos-3',
        name: 'Cozy Studio Ikeja',
        location: 'Ikeja, Lagos',
        price: 35000.00,
        imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
        description: 'Affordable studio apartment in Ikeja, close to the airport and business district.',
        bedrooms: 1,
        bathrooms: 1,
        propertyArea: '50 sqm',
        cctv: 5,
        parkingSpots: 1,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.2,
        reviewerName: 'Guest',
        reviewerImage: 'https://i.pravatar.cc/150?img=33',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      // Houses for rent – Lagos
      Property(
        id: 'lagos-h1',
        name: '4 Bedroom Semi-Detached',
        location: 'Lekki Phase 2, Lagos',
        price: 500000.00,
        imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
        description: 'Beautiful semi-detached house in Lekki Phase 2 with a private garden, fitted kitchen, and smart home features.',
        bedrooms: 4,
        bathrooms: 4,
        propertyArea: '250 sqm',
        cctv: 10,
        parkingSpots: 3,
        year: 2023,
        agent: _defaultAgent,
        rating: 4.7,
        reviewerName: 'Tunde Bakare',
        reviewerImage: 'https://i.pravatar.cc/150?img=17',
        propertyType: 'house',
        listingType: 'rent',
      ),
      Property(
        id: 'lagos-h2',
        name: '3 Bedroom Bungalow',
        location: 'Surulere, Lagos',
        price: 150000.00,
        imageUrl: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
        description: 'Well-maintained 3-bedroom bungalow in Surulere with spacious compound, tiled floors, and steady power supply.',
        bedrooms: 3,
        bathrooms: 2,
        propertyArea: '130 sqm',
        cctv: 4,
        parkingSpots: 2,
        year: 2021,
        agent: _defaultAgent,
        rating: 4.3,
        reviewerName: 'Amaka Okonkwo',
        reviewerImage: 'https://i.pravatar.cc/150?img=22',
        propertyType: 'house',
        listingType: 'rent',
      ),
    ];
  }

  static List<Property> getPortHarcourtProperties() {
    return [
      Property(
        id: 'ph-1',
        name: 'Riverside Apartment',
        location: 'GRA Phase 2, Port Harcourt',
        price: 75000.00,
        imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
        description: 'Beautiful apartment in the GRA close to the city center and major amenities.',
        bedrooms: 3,
        bathrooms: 2,
        propertyArea: '130 sqm',
        cctv: 10,
        parkingSpots: 2,
        year: 2024,
        agent: _defaultAgent,
        rating: 4.5,
        reviewerName: 'Guest',
        reviewerImage: 'https://i.pravatar.cc/150?img=33',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      Property(
        id: 'ph-2',
        name: 'Modern Villa Rumuokoro',
        location: 'Rumuokoro, Port Harcourt',
        price: 110000.00,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        description: 'Spacious modern villa in Rumuokoro with all amenities, perfect for families and extended stays.',
        bedrooms: 4,
        bathrooms: 3,
        propertyArea: '180 sqm',
        cctv: 12,
        parkingSpots: 4,
        year: 2023,
        agent: _defaultAgent,
        rating: 4.7,
        reviewerName: 'Guest',
        reviewerImage: 'https://i.pravatar.cc/150?img=1',
        propertyType: 'apartment',
        listingType: 'shortlet',
      ),
      // Houses for rent – Port Harcourt
      Property(
        id: 'ph-h1',
        name: '4 Bedroom Detached House',
        location: 'Old GRA, Port Harcourt',
        price: 280000.00,
        imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        description: 'Fully detached 4-bedroom house in Old GRA with large compound, diesel generator, and constant water supply.',
        bedrooms: 4,
        bathrooms: 4,
        propertyArea: '200 sqm',
        cctv: 8,
        parkingSpots: 3,
        year: 2022,
        agent: _defaultAgent,
        rating: 4.5,
        reviewerName: 'Boma Dike',
        reviewerImage: 'https://i.pravatar.cc/150?img=30',
        propertyType: 'house',
        listingType: 'rent',
      ),
    ];
  }

  static List<Property> getAllProperties() {
    return [
      ...getAbujaProperties(),
      ...getLagosProperties(),
      ...getPortHarcourtProperties(),
    ];
  }

  // Keep old name for backward compatibility
  static List<Property> getAllNigeriaProperties() => getAllProperties();
}
